EPOCHS: 20
BATCH_SIZE: 8
LEARNING_RATE: 0.001
LR_DECAY_RATE: 0.98


NUM_TOKENS: 8192
NUM_LAYERS: 2
NUM_RESNET_BLOCKS: 2
SMOOTH_L1_LOSS: False
EMB_DIM: 512
HID_DIM: 256
KL_LOSS_WEIGHT: 0

STARTING_TEMP: 1.
TEMP_MIN: 0.5
ANNEAL_RATE: 0.000001

NUM_IMAGES_SAVE: 4
